name: ojaewa
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+34

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  sentry_flutter: ^9.7.0
  sentry_dio: ^9.7.0
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.7
  intl: ^0.20.2
  firebase_core: ^4.3.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^18.0.1
  pusher_channels_flutter: ^2.4.0
  flutter_svg: ^2.2.3
  url_launcher: ^6.3.2
  google_sign_in: ^6.3.0
  file_picker: ^8.1.2
  path: ^1.9.1
  shared_preferences: ^2.2.2
  app_links: ^6.1.1
  syncfusion_flutter_pdfviewer: ^32.1.24
  audioplayers: ^5.2.1
  
  # In-App Purchases
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6
  in_app_purchase_storekit: ^0.3.18
  
  #Utils
  change_app_package_name: ^1.5.0
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4


flutter:

  uses-material-design: true

  assets:
    - assets/cox.mp4
    - assets/
    - assets/fonts/
    - assets/docs/
    - assets/icons/
    - assets/app_icon/

  fonts:
    - family: Campton
      fonts:
        - asset: assets/fonts/CamptonThin.otf
          weight: 100
        - asset: assets/fonts/CamptonExtraLight.otf
          weight: 200
        - asset: assets/fonts/CamptonLight.otf
          weight: 300
        - asset: assets/fonts/CamptonBook.otf
          weight: 400
        - asset: assets/fonts/CamptonMedium.otf
          weight: 500
        - asset: assets/fonts/CamptonSemiBold.otf
          weight: 600
        - asset: assets/fonts/CamptonBold.otf
          weight: 700
        - asset: assets/fonts/CamptonExtraBold.otf
          weight: 800
        - asset: assets/fonts/CamptonBlack.otf
          weight: 900